Grafana Dashboard Doc Updates
verrazzano/docs pull request #965
Opened 2023-03-27 14:43 UTC by vanajaguru

Doc updates for Grafana Enhancements- (VZ-8787)

2023-03-27 17:47 UTC, david-cabelus-oracle reviewed
Hi Vanaja,
I think we created a fair amount of value with the improvements to the Grafana dashboards that we ship in Verrazzano 1.5. In my comments, I am trying to make sure that we are highlighting the functionality that was added.

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +The dashboards in Grafana are organized into folders, and each folder represents a Kubernetes workspace.
I think you mean "namespace," not workspace.
If it is namespace, I think this information is somewhat incorrect. For example, we have folders in Grafana named Coherence, Helidon, and WebLogic, but there are no such namespaces in my Verrazzano instance.

It is hard to give complete comments without seeing the rest of the file. I will try to build the docs later today, if I get time...

The general idea for this section should be that Verrazzano installs a number of preconfigured dashboards in Grafana so that you can monitor your applications, the Kubernetes clusters where your applications are running, and Verrazzano itself. The dashboards are organized logically so that you can easily find a dashboard to view the metrics that you need to see. You can add to these dashboards, and you can copy and modify the preconfigured dashboards.

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +- NGINX dashboard provides a rich collection of Prometheus metrics such as request volume, connections, success rates, config reloads, network pressure, and so on.
When you say "Prometheus metrics," do you mean that they are metrics related to Prometheus or metrics that are generated in Prometheus format? I believe it is the latter.
If so, then I think you need to describe the source of the metrics. Is this from a load balancer? from all ingresses?

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +- OpenSearch dashboard provides metrics of the OpenSearch data such as cluster health, shard details, index details, JVM metrics, and so on.
"provides metrics of the OpenSearch data" should be "provides metrics from the OpenSearch cluster"

"of" vs "from" should be a global replacement, I think.

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +- Verrazzano Application dashboard provides information of the overall health and performance of the OAM applications that are deployed in Verrazzano, and the details of the running pods in an applic
We need a section that describes this dashboard in more detail. This is a really handy dashboard that gets updated whenever you deploy a new application in Verrazzano. You can pick which application you want to monitor, as well as pick which metrics are important to you. 

I think the bullet here is fine if we have a more detailed section with more details.

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +- Verrazzano Monitoring dashboards has a set of dashboards for `kubernetes-mixin` and `node-exporter-mixin`, and dashboards for `alertmanager-mixin` and `etcd-mixin`.  `kubernetes-mixin` dashboards c
maybe this should be sub-bullets with the details of each metrics source? You mention details on 2 of the 4, but it leaves an open question.

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +- Verrazzano System dashboards provide information of the health of all Verrazzano system components and the resource usage of the Kubernetes resources across the cluster. For resource usage, you can
It would be good to have more details on the three dashboards in this folder, similar to the request for the Verrazzano Application dashboard.

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +To view the application metrics for the `todo-list` example application, click `WebLogic` and then select `WebLogic Server Dashboard` because the `todo-list` application is a WebLogic application.
this note assumes that you have the todo-list application deployed. I don't think we can assume that.

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +The Verrazzano Grafana instance supports dynamic dashboard discovery. This lets you to package the dashboard as ConfigMaps and deploy dashboards along with other application components in Grafana.
This sentence is confusing. you don't deploy application components in Grafana.

General: When you configure a Grafana dashboard in a configmap, Verrazzano (not Verrazzano Grafana) can dynamically deploy that dashboard in the Verrazzano Grafana instance. With this capability, you can create individual configmaps in your Kubernetes clusters, or you can bundle the dashboard configmap with your application. 

Question: for configmaps, do they have to be created in the admin cluster? What happens if I create them in a managed cluster? (Note that deploying an application to a remote cluster with a dashboard configmap should work fine.)

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +- name of the `k8s-sidecar-target-directory` as `MyDashboardFolder` to place the dashboard in a custom folder in Grafana
We need more information about the label and about target directory in the introductory paragraph. this is important information.

Does the main feature need to be enabled in any way?
Is there some way to turn it off?
Are there settings related to the grafana_dashboard label?

2023-03-27 17:47 UTC, david-cabelus-oracle commented on content/en/docs/images/grafana-initial-page.png
I think you need to show the whole list. I can't really see if that is the case. If so, great!

2023-03-28 17:20 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +- name of the `k8s-sidecar-target-directory` as `MyDashboardFolder` to place the dashboard in a custom folder in Grafana
Not clear about what is the main feature.

2023-03-30 17:15 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +- name of the `k8s-sidecar-target-directory` as `MyDashboardFolder` to place the dashboard in a custom folder in Grafana
Thanks Davis for the elaborate response.

2023-04-04 12:36 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +- Istio and JVM are third-party dashboards. Istio dashboard provide metrics for Istio component that is installed as part of Verrazzano. JVM dashboard provides metrics for SpringBoot and Micronaut ap
I have removed the grouping and listed all the folders with description.

2023-04-04 12:37 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +The dashboards in Grafana are organized into folders, and each folder represents a Kubernetes workspace.
I have updated the content for Grafana dashboards

2023-04-04 12:38 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +- NGINX dashboard provides a rich collection of Prometheus metrics such as request volume, connections, success rates, config reloads, network pressure, and so on.
Updated description for NGINX dashboard

2023-04-04 12:38 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +- OpenSearch dashboard provides metrics of the OpenSearch data such as cluster health, shard details, index details, JVM metrics, and so on.
Updated the content as required

2023-04-04 12:38 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +- Verrazzano Application dashboard provides information of the overall health and performance of the OAM applications that are deployed in Verrazzano, and the details of the running pods in an applic
Added a section for Grafana Verrazzano dashboards

2023-04-04 12:38 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +To view the application metrics for the `todo-list` example application, click `WebLogic` and then select `WebLogic Server Dashboard` because the `todo-list` application is a WebLogic application.
Updated the content and provided link to the "ToDo" List application topic under "Examples"

2023-04-04 12:38 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +The Verrazzano Grafana instance supports dynamic dashboard discovery. This lets you to package the dashboard as ConfigMaps and deploy dashboards along with other application components in Grafana.
Updated the ConfigMaps section

2023-04-04 12:39 UTC, vanajaguru commented on content/en/docs/images/grafana-initial-page.png
Added the graphic that has all the folders listed

2023-04-14 15:20 UTC, david-cabelus-oracle reviewed
Hi Vanaja. Please see my comments. I also made some comments in Rosemary's checkin. I think she is addressing those. See https://github.com/verrazzano/docs/commit/0951580368a24fbe51878d7ad9fec4aac5c3ea34.

2023-04-14 15:20 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +You can use dashboard ConfigMaps to deploy custom dashboards without accessing the Grafana console. You cannot modify and save these dashboard ConfigMaps in the Grafana console; if you modify the das
This is not important: "You can use dashboard ConfigMaps to deploy custom dashboards without accessing the Grafana console."

2023-04-14 15:20 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +Verrazzano can dynamically deploy Grafana dashboards that are configured in a ConfigMap, in the Verrazzano Grafana instance. You can create individual ConfigMaps in your Kubernetes clusters or packag
We might need a little bit more here: what controls this behavior? Can I embed the JSON in the config map or do I have to refer to a separate JSON file? If I want to refer to a JSON file, where does that need to be? Folder handling?

2023-04-14 15:20 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +
I'm having trouble following this. It might be that I have my own preconceived notions...
I am expecting that I can do something like kubectl apply a config map, and that configmap would have the full definition of the dashboard. I can also add the configmap as a component, and then list that component in my OAM application configuration. I don't know that I need a JSON file.

2023-04-17 16:55 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +You can use dashboard ConfigMaps to deploy custom dashboards without accessing the Grafana console. You cannot modify and save these dashboard ConfigMaps in the Grafana console; if you modify the das
Can we change this to "You can use dashboard ConfigMaps to deploy custom dashboards." or should we remove the line "You can use dashboard ConfigMaps to deploy custom dashboards without accessing the Grafana console."

2023-04-21 17:28 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +### Dynamic dashboard discovery and portability
@david-cabelus-oracle , please review the updates to the dashboard discovery section.

2023-04-21 18:23 UTC, david-cabelus-oracle requested changes
Hi Vanaja,
Looks really good. Two corrections needed, then we are good to go!
Thanks,
Dave

2023-04-21 18:23 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +1. Access Grafana. See [Grafana](#grafana).
I don't think you need to access Grafana in Verrazzano to do this. You can download the JSON for a dashboard from a number of places.

2023-04-21 18:23 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +   - Name of the JSON file that contains the dashboard JSON.
I think this should be "JSON code that defines and configures the dashboard."

Note that in the example configmap, you show JSON code and you don't show a reference to a file that includes the JSON. The requirement should map to the example.

2023-04-21 18:33 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +You can use dashboard ConfigMaps to deploy custom dashboards; these dashboards cannot be modified or saved.   If you modify the dashboard, then you must save it as a new dashboard.
You can modify them (I think) but you just can't save them _in Grafana_. You have to either update the ConfigMap or as you point out, save the dashboard to a new location from the Grafana UI.

2023-04-21 18:33 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +2. Create a ConfigMap file in the _admin_ cluster as follows:
There's nothing special about the admin cluster. User can run Grafana on managed clusters too, if they choose. I would either remove the reference to the cluster completely, or say something about creating the ConfigMap on the same cluster running Grafana.

2023-04-21 18:33 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
"Data source" in Grafana has a meaning that's unrelated to dashboards. I would remove that text.

2023-04-21 18:33 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
The text in the NOTE doesn't really make sense, I would remove it.

2023-04-21 18:33 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +   - Name of the `k8s-sidecar-target-directory` as `MyDashboardFolder` to place the dashboard in a custom folder in Grafana.
This wording doesn't make sense. The user specifies the Grafana folder name that they want the dashboard to appear in by specifying a `k8s-sidecar-target-directory` annotation on the ConfigMap. The value of the annotation is the Grafana folder name.
The annotation is optional. If not specified, the dashboard will appear in the default Grafana folder.

2023-04-21 18:43 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
@fredtibbitts  - I had commented that the user has no idea what this label does. We could use some explanation of that. I agree that the current note is not correct. Maybe you can give us some ideas on text for the behavior? 

Just thinking about this now...

"The ConfigMap for the dashboard must include the "grafana_dashboard" label set to "1". Verrazzano looks for this label in the ConfigMap. If it finds the label, it will [do something...extract the dashboard JSON and deploy that to the Grafana instance in Verrazzano]."

2023-04-21 18:50 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
The existing wording "The `grafana_dashboard` label must be set to..." is confusing. How about something like "Grafana will automatically discover dashboard ConfigMaps that are labeled with `grafana_dashboard: "1"`?

2023-04-21 18:51 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
@david-cabelus-oracle yes a ConfigMap in a multicluster app component will work the same way. As long as the ConfigMap has the `grafana_dashboard` label and Grafana is running on the target cluster, Grafana will discover the dashboard.

2023-04-21 19:06 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
@fredtibbitts  - is it Grafana that discovers it, or is it Verrazzano that discovers it and then deploys the dashboard in Grafana? 
I assumed that something in the Verrazzano operators did the discovery.

2023-04-21 19:10 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
No not Verrazzano, we added a sidecar container to the Grafana pod that does all the discovery and dashboard loading.

2023-04-21 19:13 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
but that sidecar is something that is part of Verrazzano, right? It is not part of the Grafana open source project.

Maybe I am splitting hairs here! I won't belabor this...

2023-04-21 19:19 UTC, fredtibbitts commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
It's not part of Grafana, but it's not something the Verrazzano team wrote. This is what we're using: https://github.com/kiwigrid/k8s-sidecar.

I don't know whether you consider that "Verrazzano" or not in this context.

2023-04-24 14:39 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +1. Access Grafana. See [Grafana](#grafana).
I will remove step1.

How about the introductory statement. Do we need any changes here?
"Verrazzano enables dynamic discovery of Grafana dashboards. Using this feature, you can package the dashboard configuration and settings as a Kubernetes ConfigMap, and then deploy it individually or along with your application."

2023-04-24 14:39 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +You can use dashboard ConfigMaps to deploy custom dashboards; these dashboards cannot be modified or saved.   If you modify the dashboard, then you must save it as a new dashboard.
Is the below updated content ok?
You can use dashboard ConfigMaps to deploy custom dashboards; these dashboards can be modified but cannot be saved in Grafana.   If you want to modify the dashboard, then update the ConfigMap, or save it as a new dashboard from the Grafana UI.

2023-04-24 14:39 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
I have removed "data source".

2023-04-24 18:35 UTC, david-cabelus-oracle reviewed
Hi Vanaja. I can't tell if the changes are actually made in the files, or if they are just suggestions that you plan to incorporate. When the changes are made, I will approve the pull request.
Thanks,
Dave

2023-04-24 18:35 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +1. Access Grafana. See [Grafana](#grafana).
Looks good. Thank you!

2023-04-24 18:35 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +   - The `grafana_dashboard` label must be set to `"1"` so that Grafana selects this ConfigMap as a data source for a dashboard. **NOTE**: Use this label _only_ for the `grafana_dashboard`.
These instructions look correct to me.

2023-04-24 18:35 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +You can use dashboard ConfigMaps to deploy custom dashboards; these dashboards cannot be modified or saved.   If you modify the dashboard, then you must save it as a new dashboard.
I think that description is good enough.

2023-04-25 04:41 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +1. Access Grafana. See [Grafana](#grafana).
Hi David,
I have incorporated the changes in the file. Please take a look.

2023-04-25 15:28 UTC, vanajaguru commented
Thanks Dave for your help and reviews.

2023-04-25 15:43 UTC, rosemarymarano reviewed
Mostly suggestions, some edits.

2023-04-25 15:43 UTC, rosemarymarano commented on content/en/docs/monitoring/metrics/metrics.md
> +2. Create a ConfigMap file on the same cluster that Grafana is running using:
-> Create a ConfigMap on the same cluster running Grafana that includes:

2023-04-25 15:43 UTC, rosemarymarano commented on content/en/docs/monitoring/metrics/metrics.md
> +   - `grafana_dashboard`:`"1"` so that Grafana selects this ConfigMap.
-> - The label, `grafana_dashboard`:`"1"`, so that Grafana discovers the dashboard.

2023-04-25 15:43 UTC, rosemarymarano commented on content/en/docs/monitoring/metrics/metrics.md
> +   - dashboard JSON from step 1.
->  - The JSON code that defines and configures the dashboard (the dashboard JSON from step 1).

2023-04-25 15:43 UTC, rosemarymarano commented on content/en/docs/monitoring/metrics/metrics.md
> +   - `k8s-sidecar-target-directory` annotation to specify the Grafana folder name. If the value is
-> - Optionally, a `k8s-sidecar-target-directory` annotation, which specifies the Grafana folder name in which you want the dashboard to appear. The value of the annotation is the Grafana folder name. If not specified, the dashboard will appear in the default Grafana folder.

2023-04-25 15:43 UTC, rosemarymarano commented on content/en/docs/monitoring/metrics/metrics.md
> +You can also create a ConfigMap from a file using `kubectl create configmap`, or generate ConfigMap from files. See [Create a ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/confi
-> Alternatively, you can create a ConfigMap from a file using `kubectl create configmap` or generate a ConfigMap from files. See...

2023-04-25 16:18 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +   - `grafana_dashboard`:`"1"` so that Grafana selects this ConfigMap.
The introductory statement is "Verrazzano enables dynamic discovery of Grafana dashboards. Using this feature, you can package the dashboard configuration and settings as a Kubernetes ConfigMap, and then deploy it individually or along with your application." 
Hence I preferred to use "Grafana select this ConfigMap" rather than "Grafana discovers the dashboard". Please let me know your thoughts.
I will incorporate all other suggested changes.

2023-04-25 18:13 UTC, rosemarymarano commented on content/en/docs/monitoring/metrics/metrics.md
> +   - `grafana_dashboard`:`"1"` so that Grafana selects this ConfigMap.
Here is a compilation of the questions and answers about the grafana_dashboard label:
From Davis -
The Grafana dashboard label must be grafana_dashboards: “1”. Otherwise, our existing system dashboards will not be collected by Grafana. This could potentially be improved or altered in the future if needed.
From Dave:
Regarding the grafana_dashboards label:
   -  what exactly does this control? (this info may or may not be important to the end user)
    - what does "Otherwise, our existing system dashboards will not be collected by Grafana" mean? This sounds scary as written. What will break if this label is not set to 1?
    - What are the valid values for the label? What happens if I set it to an invalid value?
From Dave to Fred:
I had commented that the user has no idea what this label does. We could use some explanation of that. I agree that the current note is not correct. Maybe you can give us some ideas on text for the behavior?
Just thinking about this now...
"The ConfigMap for the dashboard must include the "grafana_dashboard" label set to "1". Verrazzano looks for this label in the ConfigMap. If it finds the label, it will [do something...extract the dashboard JSON and deploy that dashboard to the Grafana instance in Verrazzano]."
From Fred:
The existing wording "The grafana_dashboard label must be set to..." is confusing. How about something like "**Grafana will automatically discover dashboard ConfigMaps that are labeled with grafana_dashboard: "1"**
Yes, a ConfigMap in a multicluster app component will work the same way. As long as the ConfigMap has the grafana_dashboard label and Grafana is running on the target cluster, **Grafana will discover the dashboard**.
Then they debate whether it's Verrazzano or Grafana that actually does the dashboard discovery. Fred: No not Verrazzano, we added a sidecar container to the Grafana pod that does all the discovery and dashboard loading.

I thought that Fred's knowledge and description was probably the best one to follow, that's why I chose that text. You are free to choose otherwise.

2023-04-25 18:39 UTC, david-cabelus-oracle commented on content/en/docs/monitoring/metrics/metrics.md
> +   - `grafana_dashboard`:`"1"` so that Grafana selects this ConfigMap.
Makes sense. Sorry if my comment came across the wrong way! 

I think all of us have the knowledge from the comments that you mention, but the reader now has 1 line to understand what the label does: `grafana_dashboard`:`"1"` so that Grafana selects this ConfigMap.  

I was hoping for a little more detail around this feature and its behavior, somewhat for this particular feature, but also as a general expectation around what we want for documentation. If we can give users information about how the system is designed and how it behaves, they can better use the system. 

I'm happy to have this documentation done, though! Let's move on to more critical items. :-)

2023-04-26 06:59 UTC, vanajaguru commented on content/en/docs/monitoring/metrics/metrics.md
> +   - `grafana_dashboard`:`"1"` so that Grafana selects this ConfigMap.
Rosemary, I have incorporated your suggestions.

2023-04-26 10:14 UTC, rosemarymarano approved these changes

2023-04-26 14:57 UTC, vanajaguru commented
Closing this PR due to merge conflicts. Updates are merged via https://github.com/verrazzano/docs/pull/1039

2023-04-26 14:57 UTC, closed without merging